export const GET_CONVERSATION = 'GET_CONVERSATION';
export const GET_CONVERSATION_SUCCESS = 'GET_CONVERSATION_SUCCESS';

export const GET_MESSAGE = 'GET_MESSAGE';
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_STATUS_LOADING = 'SEND_MESSAGE_STATUS_LOADING';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const ON_NEW_MESSGAGE = 'ON_NEW_MESSGAGE';

export const CHANGE_ACTIVE = 'CHANGE_ACTIVE';
export const GET_OR_CREATE_CONVERSATION = 'GET_OR_CREATE_CONVERSATION'
export const GET_OR_CREATE_CONVERSATION_SUCCESS = 'GET_OR_CREATE_CONVERSATION_SUCCESS'
export const CONVERSATION_CHANGE_STATE = 'CONVERSATION_CHANGE_STATE'
