export const GET_CONVERSATION = 'GET_CONVERSATION';
export const GET_CONVERSATION_SUCCESS = 'GET_CONVERSATION_SUCCESS';

export const CHANGE_ACTIVE = 'CHANGE_ACTIVE';
export const GET_OR_CREATE_CONVERSATION = 'GET_OR_CREATE_CONVERSATION'
export const GET_OR_CREATE_CONVERSATION_SUCCESS = 'GET_OR_CREATE_CONVERSATION_SUCCESS'
export const CONVERSATION_CHANGE_STATE = 'CONVERSATION_CHANGE_STATE'
