export const GET_PROFILE_USER: string = 'GET_PROFILE_USER';
export const GET_PROFILE_USER_SUCCESS: string = 'GET_PROFILE_USER_SUCCESS';
export const GET_PROFILE_USER_FAIL: string = 'GET_PROFILE_USER_FAIL';

export const PROFILE_CHANGE_AVATAR: string = 'PROFILE_CHANGE_AVATAR';
export const PROFILE_CHANGE_AVATAR_SUCCESS: string = 'PROFILE_CHANGE_AVATAR_SUCCESS';
export const PROFILE_CHANGE_AVATAR_FAIL: string = 'PROFILE_CHANGE_AVATAR_FAIL';

export const PROFILE_CHANGE_COVER: string = 'PROFILE_CHANGE_COVER';
export const PROFILE_CHANGE_COVER_SUCCESS: string = 'PROFILE_CHANGE_COVER_SUCCESS';
export const PROFILE_CHANGE_COVER_FAIL: string = 'PROFILE_CHANGE_COVER_FAIL';

export const PROFILE_POST_ARTICLE: string = 'PROFILE_POST_ARTICLE';
export const PROFILE_POST_ARTICLE_SUCCESS: string = 'PROFILE_POST_ARTICLE_SUCCESS';
export const PROFILE_POST_ARTICLE_FAIL: string = 'PROFILE_POST_ARTICLE_FAIL';

export const PROFILE_GET_ARTICLES: string = 'PROFILE_GET_ARTICLES';
export const PROFILE_GET_ARTICLES_SUCCESS: string = 'PROFILE_GET_ARTICLES_SUCCESS';
export const PROFILE_GET_ARTICLES_FAIL: string = 'PROFILE_GET_ARTICLES_FAIL';

export const PROFILE_DELETE_ARTICLE: string = 'PROFILE_DELETE_ARTICLE';
export const PROFILE_DELETE_ARTICLE_SUCCESS: string = 'PROFILE_DELETE_ARTICLE_SUCCESS';
export const PROFILE_DELETE_ARTICLE_FAIL: string = 'PROFILE_DELETE_ARTICLE_FAIL';

export const PROFILE_CHANGE_STATE: string = 'PROFILE_CHANGE_STATE';
