export const GET_PROFILE_USER = 'GET_PROFILE_USER';
export const PROFILE_CHANGE_AVATAR = 'PROFILE_CHANGE_AVATAR';
export const PROFILE_CHANGE_STATE = 'PROFILE_CHANGE_STATE';
export const PROFILE_CHANGE_AVATAR_SUCCESS = 'PROFILE_CHANGE_AVATAR_SUCCESS';
export const PROFILE_CHANGE_AVATAR_FAIL = 'PROFILE_CHANGE_AVATAR_FAIL';
