export const GET_PROFILE_USER = 'GET_PROFILE_USER';
export const GET_PROFILE_USER_SUCCESS = 'GET_PROFILE_USER_SUCCESS';
export const GET_PROFILE_USER_FAIL = 'GET_PROFILE_USER_FAIL';

export const PROFILE_CHANGE_AVATAR = 'PROFILE_CHANGE_AVATAR';
export const PROFILE_CHANGE_AVATAR_SUCCESS = 'PROFILE_CHANGE_AVATAR_SUCCESS';
export const PROFILE_CHANGE_AVATAR_FAIL = 'PROFILE_CHANGE_AVATAR_FAIL';

export const PROFILE_POST_ARTICLE = 'PROFILE_POST_ARTICLE';
export const PROFILE_POST_ARTICLE_SUCCESS = 'PROFILE_POST_ARTICLE_SUCCESS';
export const PROFILE_POST_ARTICLE_FAIL = 'PROFILE_POST_ARTICLE_FAIL';

export const PROFILE_GET_ARTICLES = 'PROFILE_GET_ARTICLES';
export const PROFILE_GET_ARTICLES_SUCCESS = 'PROFILE_GET_ARTICLES_SUCCESS';
export const PROFILE_GET_ARTICLES_FAIL = 'PROFILE_GET_ARTICLES_FAIL';

export const PROFILE_CHANGE_STATE = 'PROFILE_CHANGE_STATE';
