export const HOME_GET_USER_RECOMMENT = 'HOME_GET_USER_RECOMMENT';
export const HOME_GET_USER_RECOMMENT_SUCCESS = 'HOME_GET_USER_RECOMMENT_SUCCESS';
export const HOME_GET_USER_RECOMMENT_FAIL = 'HOME_GET_USER_RECOMMENT_FAIL';

export const FOLLOW_USER = 'FOLLOW_USER';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAIL = 'FOLLOW_USER_FAIL';

export const HOME_CHANGE_STATE = 'HOME_CHANGE_STATE';
