export const HOME_GET_USER_RECOMMENT: string = 'HOME_GET_USER_RECOMMENT';
export const HOME_GET_USER_RECOMMENT_SUCCESS: string = 'HOME_GET_USER_RECOMMENT_SUCCESS';
export const HOME_GET_USER_RECOMMENT_FAIL: string = 'HOME_GET_USER_RECOMMENT_FAIL';

export const FOLLOW_USER: string = 'FOLLOW_USER';
export const FOLLOW_USER_SUCCESS: string = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAIL: string = 'FOLLOW_USER_FAIL';

export const HOME_GET_ARTICLE: string = 'HOME_GET_ARTICLE';
export const HOME_GET_ARTICLE_SUCCESS: string = 'HOME_GET_ARTICLE_SUCCESS';
export const HOME_GET_ARTICLE_FAIL: string = 'HOME_GET_ARTICLE_FAIL';

export const HOME_CHANGE_STATE: string = 'HOME_CHANGE_STATE';
