export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';

export const GET_NOTIFICATION_UNSEEN = 'GET_NOTIFICATION_UNSEEN';
export const GET_NOTIFICATION_UNSEEN_SUCCESS = 'GET_NOTIFICATION_UNSEEN_SUCCESS';
export const NOTIFICATION_UNSEEN_SUCCESS = 'NOTIFICATION_UNSEEN_SUCCESS';

export const ON_NEW_NOTIFICATION = 'ON_NEW_NOTIFICATION';
