export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_UP_SHOW_LOADING = 'SIGN_UP_SHOW_LOADING';
export const SIGN_UP_HIDE_LOADING = 'SIGN_UP_HIDE_LOADING';
export const SIGN_UP_CHANGE_STATE = 'SIGN_UP_CHANGE_STATE';
export const SIGN_UP_CLEAR_STATE = 'SIGN_UP_CLEAR_STATE';
